import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>This is a main section.</h2>
      </main>

      <footer className={styles.footer}>
        <p>This is footer section.</p>
      </footer>
    </div>
  );
}
